using System.Data;
using System.IO;
namespace Hisab;
public static class V2Tests
{
    public static void Run(string directory,List<string> results)
    {
        void Check(bool ok,string name){if(!ok)throw new Exception(name);results.Add("PASS "+name);}
        void Reject(Action action,string name){bool rejected=false;try{action();}catch(InvalidOperationException){rejected=true;}Check(rejected,name);}
        string path=Path.Combine(directory,"encrypted.hdb");long count;
        using(var s=new Store(path,true)){
            var a=new AccountingService(s);var day=DateTime.Today.AddDays(-20);var c=s.Accounts().First(x=>x.Kind=="Unclassified");s.SaveAccount(c.Id,c.Code,c.Name,"Customer");var p=s.Accounts().First(x=>x.Kind=="Unclassified");s.SaveAccount(p.Id,p.Code,p.Name,"Supplier");long cash=s.AccountId("1101");var item=s.Items()[0];
            a.Invoice(false,day,p.Id,null,0,16,false,"Stock",[new(item.Id,"Stock",10,100,0)]);
            long sale=a.Invoice(true,day.AddDays(2),c.Id,null,0,16,false,"Sale",[new(item.Id,"Stock",4,150,0)]);
            long receipt=a.Voucher(true,day.AddDays(3),c.Id,cash,200,"Receipt");a.Allocate(receipt,sale,200,day.AddDays(3));
            Check(a.Positions(day.AddDays(2)).Single(x=>x.Invoice==sale).Paid==0,"Historical invoice balance excludes later receipts");
            Check(a.Positions(DateTime.Today).Single(x=>x.Invoice==sale).Outstanding==496000,"Partial receipt allocated to invoice");Reject(()=>a.Allocate(receipt,sale,1,DateTime.Today),"Voucher over-allocation rejected");
            long line=Convert.ToInt64(s.Scalar("SELECT id FROM invoice_lines WHERE doc=@p0",sale));long ret=a.ReturnInvoice(sale,day.AddDays(4),[new(line,1)],"Returned unit");Check(a.Positions(DateTime.Today).Single(x=>x.Invoice==sale).Returned==174000,"Sales return reduces invoice outstanding");Reject(()=>a.ReturnInvoice(sale,day.AddDays(5),[new(line,4)],"Too much"),"Excess returns rejected");Reject(()=>a.Reverse(sale,"Has returns"),"Source with live returns cannot cancel");a.Reverse(ret,"Undo return",day.AddDays(5));
            Check(a.TaxEvents(day,day.AddDays(4)).Rows.Cast<DataRow>().Where(r=>r["kind"].ToString() is "SI" or "SR").Sum(r=>(long)r["tax"]*(long)r["sign"])==72000,"Past tax worksheet includes dated return despite later cancellation");
            long amended=a.AmendInvoice(sale,true,day.AddDays(2),c.Id,null,0,16,false,"Corrected",[new(item.Id,"Stock",3,150,0)],"Quantity correction");Check(a.Positions(DateTime.Today).Single(x=>x.Invoice==amended).Paid==200000,"Invoice amendment transfers allocations atomically");Check(Convert.ToInt64(s.Scalar("SELECT count(*) FROM revisions"))==1,"Amendments preserve reason and original snapshot");
            long purchase=a.Invoice(false,day.AddDays(1),p.Id,null,0,0,false,"Backdated",[new(item.Id,"Stock",10,200,0)]);Check(s.Items()[0].Value==2550000,"Backdated purchase replays subsequent weighted cost");
            long piLine=Convert.ToInt64(s.Scalar("SELECT id FROM invoice_lines WHERE doc=@p0",purchase));a.ReturnInvoice(purchase,day.AddDays(6),[new(piLine,2)],"Supplier return");Check(s.Items()[0].Qty==15000,"Purchase returns reduce stock");a.RevalueStock(item.Id,175,"Verified valuation");Check(s.Items()[0].Value==2625000,"Audited cost adjustment changes stock valuation");
            long issue=a.RegisterCheque(true,"1001","Test bank",c.Id,100,day.AddDays(7),day.AddDays(9),amended);long cheque=Convert.ToInt64(s.Scalar("SELECT id FROM cheques WHERE issue_doc=@p0",issue));a.SettleCheque(cheque,"Cleared",cash,day.AddDays(9),"Cleared");a.SettleCheque(cheque,"Bounced",cash,day.AddDays(10),"Returned by bank");Check(a.Positions(DateTime.Today).Single(x=>x.Invoice==amended).Paid==200000,"Bounced cheque releases allocations");Check(s.Scalar("SELECT reversal_date FROM documents WHERE id=@p0",issue)?.ToString()==day.AddDays(10).ToString("yyyy-MM-dd"),"Cheque reversal uses selected historical date");Reject(()=>a.SettleCheque(cheque,"Cleared",cash,DateTime.Today,"Again"),"Terminal cheque cannot clear again");
            var second=s.Items()[1];s.Set("allow_negative","1");a.Invoice(true,day,c.Id,null,0,0,false,"Negative",[new(second.Id,"Negative",2,150,0)]);Check(s.Items()[1].Qty==-2000,"Optional negative stock supported");a.Invoice(false,day.AddDays(1),p.Id,null,0,0,false,"Cover",[new(second.Id,"Cover",3,100,0)]);Check(s.Items()[1].Value==100000,"Receipt reconciles provisional negative-stock costing");
            Check(s.Balance(s.AccountId("1301"))==s.Items().Sum(x=>x.Value),"Extended inventory ledger equals valuation");Check(Convert.ToInt64(s.Scalar("SELECT count(*) FROM (SELECT doc FROM entries GROUP BY doc HAVING sum(debit)!=sum(credit))"))==0,"All extended journals balance");
            a.CloseYear(day,day.AddDays(10));Reject(()=>a.Voucher(true,day,c.Id,cash,10,"Closed"),"Closed period rejects posting");Reject(()=>a.AmendInvoice(amended,true,day.AddDays(2),c.Id,null,0,16,false,"Closed",[new(item.Id,"Stock",1,150,0)],"Closed"),"Closed invoice rejects amendment");long period=Convert.ToInt64(s.Scalar("SELECT id FROM periods"));a.ReopenYear(period,"Administrator correction");Check(Convert.ToInt64(s.Scalar("SELECT count(*) FROM periods"))==0,"Administrator reopens period with reversal");
            string attachment=Path.Combine(directory,"attachment.txt");File.WriteAllText(attachment,"private invoice attachment");s.AddAttachment(amended,attachment);Check(Convert.ToInt64(s.Scalar("SELECT count(*) FROM attachments"))==1,"Attachment persisted within database");
            s.SaveTranslations("accounts",c.Id,"اسم عربي","English customer","عنوان عربي","English address");Check(s.LocalName("accounts",c.Id,false)=="English customer","Editable bilingual account names");
            s.SaveUser("admin","AdminPassword123","Admin");s.SaveUser("reader","ReaderPassword123","Viewer");Check(!s.Login("reader","wrong"),"Incorrect password rejected");Check(s.Login("reader","ReaderPassword123"),"Viewer can authenticate");Reject(()=>a.Voucher(true,DateTime.Today,c.Id,cash,1,"Forbidden"),"Viewer cannot post via accounting service");Reject(()=>s.Set("company","Forbidden"),"Viewer cannot change business settings");Check(s.Login("admin","AdminPassword123"),"Administrator can authenticate");
            string backup=Path.Combine(directory,"portable.hisab");s.PortableBackup(backup,"BackupPassword123");count=Convert.ToInt64(s.Scalar("SELECT count(*) FROM documents"));a.Voucher(true,DateTime.Today,c.Id,cash,5,"After backup");Reject(()=>s.RestorePortable(backup,"WrongPassword123"),"Wrong backup password rejected");s.RestorePortable(backup,"BackupPassword123");Check(Convert.ToInt64(s.Scalar("SELECT count(*) FROM documents"))==count,"Encrypted portable backup restores snapshot");
            Check(s.Table("PRAGMA foreign_key_check").Rows.Count==0&&s.Scalar("PRAGMA integrity_check")?.ToString()=="ok","Extended database integrity and foreign keys");
            string beforeCompany=s.Setting("company");bool saveFailed=false;using(var locked=new FileStream(path,FileMode.Open,FileAccess.Read,FileShare.Read)){try{s.Set("company","Must not persist");}catch(IOException){saveFailed=true;}catch(UnauthorizedAccessException){saveFailed=true;}}Check(saveFailed&&s.Setting("company")==beforeCompany,"Failed encrypted-file save rolls back in-memory change");
            byte[] damaged=File.ReadAllBytes(backup);damaged[^1]^=1;string corrupt=Path.Combine(directory,"corrupt.hisab");File.WriteAllBytes(corrupt,damaged);Reject(()=>s.RestorePortable(corrupt,"BackupPassword123"),"Tampered encrypted backup rejected");Check(Convert.ToInt64(s.Scalar("SELECT count(*) FROM documents"))==count,"Rejected backup preserves current data");
        }
        Check(!File.ReadAllBytes(path).AsSpan().StartsWith(System.Text.Encoding.ASCII.GetBytes("SQLite format 3")),"Local data is encrypted at rest");
        using(var reopened=new Store(path,true)){Check(Convert.ToInt64(reopened.Scalar("SELECT count(*) FROM documents"))==count,"Encrypted database survives process-style reopen");}
        using(var other=new Store(Path.Combine(directory,"other-machine.hdb"),true)){other.RestorePortable(Path.Combine(directory,"portable.hisab"),"BackupPassword123");Check(Convert.ToInt64(other.Scalar("SELECT count(*) FROM documents"))==count,"Portable backup restores under independent local encryption key");}
        string migration=Path.Combine(directory,"migration");Directory.CreateDirectory(migration);string legacy=Path.Combine(migration,"accounting.db");using(var old=new Store(legacy)){old.Exec("PRAGMA user_version=1");Directory.CreateDirectory(Path.Combine(migration,"backups"));old.Backup(Path.Combine(migration,"backups","automatic-old.db"));}
        using(var migrated=new Store(Path.Combine(migration,"accounting.hdb"),true)){Check(migrated.Items().Count==17&&Convert.ToInt32(migrated.Scalar("PRAGMA user_version"))==2,"Legacy database migrates to encrypted schema v2");Check(!File.Exists(legacy)&&Directory.GetFiles(Path.Combine(migration,"backups"),"*.db").Length==0,"App-owned legacy plaintext database and backups replaced with encrypted files");}
    }
}
